Repository kubescape/regolibrary, pull requests merged in 2023-09, with the labels that each got.

#501 Fix control C-0211
  controls/C-0211-applysecuritycontexttoyourpodsandcontainers.json
  rules/set-sysctls-params/raw.rego
  rules/set-sysctls-params/rule.metadata.json
  rules/set-sysctls-params/test/cronjob/expected.json
  rules/set-sysctls-params/test/cronjob/input/cronjob1.yaml
  rules/set-sysctls-params/test/pod-pass/expected.json
  rules/set-sysctls-params/test/pod-pass/input/pod1.yaml
  rules/set-sysctls-params/test/pod/expected.json
  rules/set-sysctls-params/test/pod/input/pod1.yaml
  rules/set-sysctls-params/test/workload/expected.json
  rules/set-sysctls-params/test/workload/input/deployment1.yaml
Labels: Bug fix, Tests

#481 core(exceptions): Edit system exceptions
  exceptions/kubescape.json
Labels: enhancement

#502 Revert "core(exceptions): Edit system exceptions"
  exceptions/kubescape.json
Labels: Bug fix

#504 fix failpath
  rules/exposure-to-internet/raw.rego
  rules/exposure-to-internet/test/failed_with_ingress/expected.json
Labels: Bug fix

#505 change node names + add description
  attack-tracks/service-destruction.json
  attack-tracks/workload-external-track.json
  controls/C-0009-resourcelimits.json
  controls/C-0041-hostnetworkaccess.json
  controls/C-0044-containerhostport.json
  controls/C-0045-writablehostpathmount.json
  controls/C-0046-insecurecapabilities.json
  controls/C-0048-hostpathmount.json
  controls/C-0211-applysecuritycontexttoyourpodsandcontainers.json
  controls/C-0256-exposuretointernet.json
  controls/C-0257-pvcaccess.json
  controls/C-0258-configmapaccess.json
  controls/C-0260-missingnetworkpolicy.json
Labels: Refactoring

#507 remove control C-0044 (hostPort) from attack tracks
  controls/C-0044-containerhostport.json
Labels: Refactoring
