Repository kubescape/regolibrary, pull requests merged in 2023-11, with the labels that each got.

#533 adding maintainers file
  MAINTAINERS.md
Labels: documentation

#540 marking smartremediation controls
  controls/C-0016-allowprivilegeescalation.json
  controls/C-0017-immutablecontainerfilesystem.json
  controls/C-0034-automaticmappingofserviceaccount.json
  controls/C-0045-writablehostpathmount.json
  controls/C-0046-insecurecapabilities.json
  controls/C-0048-hostpathmount.json
  controls/C-0057-privilegedcontainer.json
  controls/C-0074-containersmountingdockersocket.json
  go.mod
  go.sum
Labels: enhancement

#545 Update pr-tests.yaml
  .github/workflows/pr-tests.yaml
Labels: Refactoring

#547 C-0211 - fix and improve assisted remediation
  rules/immutable-container-filesystem/raw.rego
  rules/non-root-containers/raw.rego
  rules/non-root-containers/test/cronjob/expected.json
  rules/non-root-containers/test/pod/expected.json
  rules/non-root-containers/test/pod/input/pod.yaml
  rules/set-fsgroup-value/raw.rego
  rules/set-fsgroup-value/test/cronjob/expected.json
  rules/set-fsgroup-value/test/pod/expected.json
  rules/set-fsgroup-value/test/workload/expected.json
  rules/set-procmount-default/raw.rego
  rules/set-procmount-default/test/cronjob/expected.json
  rules/set-procmount-default/test/pod/expected.json
  rules/set-procmount-default/test/workload/expected.json
  rules/set-procmount-default/test/workload/input/deployment.yaml
  rules/set-supplementalgroups-values/raw.rego
  rules/set-supplementalgroups-values/test/cronjob/expected.json
  rules/set-supplementalgroups-values/test/pod/expected.json
  rules/set-supplementalgroups-values/test/workload/expected.json
Labels: enhancement, bug_fix

#548 Remove armobuiltin
  frameworks/__YAMLscan.json
  frameworks/allcontrols.json
  frameworks/armobest.json
  frameworks/cis-aks-t1.2.0.json
  frameworks/cis-eks-t1.2.0.json
  frameworks/cis-v1.23-t1.0.1.json
  frameworks/clusterscan.json
  frameworks/devopsbest.json
  frameworks/mitre.json
  frameworks/nsaframework.json
  frameworks/security.json
  frameworks/workloadscan.json
Labels: enhancement

#549 fix release
  .github/workflows/create-release.yaml
Labels: bug_fix
