Repository kubescape/regolibrary, pull requests merged in 2023-10, with the labels that each got.

#508 start adding delete / review paths
  rules/CVE-2021-25741/raw.rego
  rules/alert-any-hostpath/raw.rego
  rules/alert-container-optimized-os-not-in-use/raw.rego
  rules/alert-mount-potential-credentials-paths/raw.rego
  rules/alert-rw-hostpath/raw.rego
  rules/anonymous-requests-to-kubelet-updated/raw.rego
  rules/automount-default-service-account/raw.rego
  rules/automount-service-account/raw.rego
  rules/cluster-admin-role/raw.rego
  rules/configmap-in-default-namespace/raw.rego
  rules/container-hostPort/raw.rego
  rules/container-image-repository-v1/raw.rego
  rules/container-image-repository/raw.rego
  rules/containers-mounting-docker-socket/raw.rego
  rules/csistoragecapacity-in-default-namespace/raw.rego
  rules/insecure-capabilities/raw.rego
Labels: enhancement

#511 Write new text for control input help.
  README.md
  rules/K8s common labels usage/rule.metadata.json
  rules/container-image-repository-v1/rule.metadata.json
  rules/container-image-repository/rule.metadata.json
  rules/excessive_amount_of_vulnerabilities_pods/rule.metadata.json
  rules/exposed-sensitive-interfaces-v1/rule.metadata.json
  rules/exposed-sensitive-interfaces/rule.metadata.json
  rules/insecure-capabilities/rule.metadata.json
  rules/label-usage-for-resources/rule.metadata.json
  rules/resources-cpu-limit-and-request/rule.metadata.json
  rules/resources-memory-limit-and-request/rule.metadata.json
  rules/rule-credentials-configmap/rule.metadata.json
  rules/rule-credentials-in-env-var/rule.metadata.json
  rules/rule-identify-blocklisted-image-registries-v1/rule.metadata.json
  rules/rule-identify-blocklisted-image-registries/rule.metadata.json
  rules/verify-image-signature/rule.metadata.json
Labels: documentation

#513 fix: change capitalisation of "pod" and "etcd" throughout
  FWName_CID_CName.csv
  README.md
  controls/C-0009-resourcelimits.json
  controls/C-0013-nonrootcontainers.json
  controls/C-0017-immutablecontainerfilesystem.json
  controls/C-0018-configuredreadinessprobe.json
  controls/C-0026-kubernetescronjob.json
  controls/C-0030-ingressandegressblocked.json
  controls/C-0034-automaticmappingofserviceaccount.json
  controls/C-0038-hostpidipcprivileges.json
  controls/C-0041-hostnetworkaccess.json
  controls/C-0045-writablehostpathmount.json
  controls/C-0046-insecurecapabilities.json
  controls/C-0048-hostpathmount.json
  controls/C-0053-accesscontainerserviceaccount.json
  controls/C-0056-configuredlivenessprobe.json
  controls/C-0057-privilegedcontainer.json
  controls/C-0061-podsindefaultnamespace.json
  controls/C-0062-sudoincontainerentrypoint.json
  controls/C-0063-portforwardingprivileges.json
  controls/C-0066-secretetcdencryptionenabled.json
  controls/C-0068-pspenabled.json
  controls/C-0073-nakedpods.json
  controls/C-0074-containersmountingdockersocket.json
  controls/C-0075-imagepullpolicyonlatesttag.json
  controls/C-0083-workloadswithcriticalvulnerabilitiesexposedtoexternaltraffic.json
  controls/C-0084-workloadswithrcevulnerabilitiesexposedtoexternaltraffic.json
  controls/C-0087-cve202223648containerdfsescape.json
  frameworks/__YAMLscan.json
  frameworks/allcontrols.json
  frameworks/armobest.json
  frameworks/cis-eks-t1.2.0.json
  frameworks/clusterscan.json
  frameworks/devopsbest.json
  frameworks/mitre.json
  frameworks/nsaframework.json
  rules/ensure_network_policy_configured_in_labels/test/failed_deployment_no_matched_label/input/deployment.yaml
  rules/ensure_network_policy_configured_in_labels/test/success_deployment_label_match/input/deployment.yaml
Labels: Refactoring

#512 Fix spelling of "beggining" throughout.
  rules/CVE-2021-25741/raw.rego
  rules/CVE-2022-0492/raw.rego
  rules/K8s common labels usage/raw.rego
  rules/alert-any-hostpath/raw.rego
  rules/alert-mount-potential-credentials-paths/raw.rego
  rules/alert-rw-hostpath/raw.rego
  rules/automount-service-account/raw.rego
  rules/container-hostPort/raw.rego
  rules/immutable-container-filesystem/raw.rego
  rules/insecure-capabilities/raw.rego
  rules/label-usage-for-resources/raw.rego
  rules/non-root-containers/raw.rego
  rules/resource-policies/raw.rego
  rules/rule-allow-privilege-escalation/raw.rego
  rules/rule-privileged-container/raw.rego
  rules/serviceaccount-token-mount/filter.rego
  rules/serviceaccount-token-mount/raw.rego
  rules/sudo-in-container-entrypoint/raw.rego
Labels: Refactoring

#514 Add .YOUR_KEY to C-0077 & C-0076
  ControlID_RuleName.csv
  controls/C-0077-k8scommonlabelsusage.json
  rules/k8s-common-labels-usage/raw.rego
  rules/k8s-common-labels-usage/rule.metadata.json
  rules/k8s-common-labels-usage/test/cronjob/data.json
  rules/k8s-common-labels-usage/test/cronjob/expected.json
  rules/k8s-common-labels-usage/test/cronjob/input/cronjob.yaml
  rules/k8s-common-labels-usage/test/pod/data.json
  rules/k8s-common-labels-usage/test/pod/expected.json
  rules/k8s-common-labels-usage/test/pod/input/pod.yaml
  rules/k8s-common-labels-usage/test/workload-fail/data.json
  rules/k8s-common-labels-usage/test/workload-fail/expected.json
  rules/k8s-common-labels-usage/test/workload-fail/input/deployment.yaml
  rules/k8s-common-labels-usage/test/workload/expected.json
  rules/k8s-common-labels-usage/test/workload/input/deployment.yaml
  rules/label-usage-for-resources/raw.rego
  rules/label-usage-for-resources/test/cronjob/data.json
  rules/label-usage-for-resources/test/cronjob/expected.json
  rules/label-usage-for-resources/test/pod/data.json
  rules/label-usage-for-resources/test/pod/expected.json
  rules/label-usage-for-resources/test/workload-fail/data.json
  rules/label-usage-for-resources/test/workload-fail/expected.json
Labels: Bug fix

#519 Improvements to control C-0262
  controls/C-0262-anonymousaccessisenabled.json
  rules/anonymous-access-enabled/raw.rego
  rules/anonymous-access-enabled/rule.metadata.json
  rules/anonymous-access-enabled/test/fail/expected.json
Labels: enhancement

#523 Fix fixpath for controls C-0077 and C-0076
  rules/k8s-common-labels-usage/raw.rego
  rules/k8s-common-labels-usage/test/cronjob/expected.json
  rules/k8s-common-labels-usage/test/pod/expected.json
  rules/k8s-common-labels-usage/test/workload-fail/expected.json
  rules/label-usage-for-resources/raw.rego
  rules/label-usage-for-resources/test/cronjob/expected.json
  rules/label-usage-for-resources/test/pod/expected.json
  rules/label-usage-for-resources/test/workload-fail/expected.json
Labels: Bug fix

#524 add missing delete paths
  rules/rule-credentials-configmap/raw.rego
Labels: Bug fix

#525 Making sure that service and ingress are in the same namespace
  controls/C-0256-exposuretointernet.json
  rules/exposure-to-internet/raw.rego
  rules/exposure-to-internet/test/failed_with_ingress/expected.json
  rules/exposure-to-internet/test/failed_with_ingress/input/ingress.yaml
  rules/exposure-to-internet/test/failed_with_ingress/input/service.yaml
Labels: Bug fix

#527 C-0004 & C-0050 - fix only missing configurations
  rules/resources-cpu-limit-and-request/raw.rego
  rules/resources-cpu-limit-and-request/test/cronjob/expected.json
  rules/resources-cpu-limit-and-request/test/pod-only-limits/expected.json
  rules/resources-cpu-limit-and-request/test/pod-only-limits/input/pod.yaml
  rules/resources-cpu-limit-and-request/test/pod-only-requests/expected.json
  rules/resources-cpu-limit-and-request/test/pod-only-requests/input/pod.yaml
  rules/resources-cpu-limit-and-request/test/pod/expected.json
  rules/resources-cpu-limit-and-request/test/workload/expected.json
  rules/resources-memory-limit-and-request/raw.rego
  rules/resources-memory-limit-and-request/test/cronjob/expected.json
  rules/resources-memory-limit-and-request/test/pod-only-limits/expected.json
  rules/resources-memory-limit-and-request/test/pod-only-limits/input/pod.yaml
  rules/resources-memory-limit-and-request/test/pod-only-requests/expected.json
  rules/resources-memory-limit-and-request/test/pod-only-requests/input/pod.yaml
  rules/resources-memory-limit-and-request/test/pod/expected.json
  rules/resources-memory-limit-and-request/test/workload/expected.json
Labels: Bug fix

#528 add missing paths
  rules/exec-into-container/raw.rego
  rules/image-pull-policy-is-not-set-to-always/raw.rego
  rules/immutable-container-filesystem/raw.rego
  rules/immutable-container-filesystem/test/workloads/expected.json
  rules/rule-can-impersonate-users-groups/raw.rego
  rules/rule-can-list-get-secrets/raw.rego
  rules/rule-can-portforward/raw.rego
  rules/rule-can-ssh-to-pod/raw.rego
  rules/rule-can-update-configmap/raw.rego
  rules/rule-credentials-in-env-var/raw.rego
Labels: enhancement

#529 separate limit and request cases so both paths can be sent
  rules/resources-cpu-limit-and-request/raw.rego
  rules/resources-memory-limit-and-request/raw.rego
Labels: Refactoring

#531 Update upload-readme.py
  scripts/upload-readme.py
Labels: Refactoring

#532 Use cluster scope instead of AKS
  controls/C-0239-preferusingdedicatedaksserviceaccounts.json
  controls/C-0240-ensurenetworkpolicyisenabledandsetasappropriate.json
  controls/C-0241-useazurerbacforkubernetesauthorization.json
  controls/C-0242-hostilemultitenantworkloads.json
  controls/C-0243-ensureimagevulnerabilityscanningusingazuredefenderimagescanningorathirdpartyprovider.json
  controls/C-0244-ensurekubernetessecretsareencrypted.json
  controls/C-0245-encrypttraffictohttpsloadbalancerswithtlscertificates.json
  controls/C-0247-restrictaccesstothecontrolplaneendpoint.json
  controls/C-0248-ensureclustersarecreatedwithprivatenodes.json
  controls/C-0249-restrictuntrustedworkloads.json
  controls/C-0250-minimizeclusteraccesstoreadonlyforazurecontainerregistryacr.json
  controls/C-0252-ensureclustersarecreatedwithprivateendpointenabledandpublicaccessdisabled.json
  controls/C-0254-enableauditlogs.json
  frameworks/cis-aks-t1.2.0.json
Labels: Bug fix

#530 fix edge case, add test cases
  rules/resources-cpu-limit-and-request/raw.rego
  rules/resources-cpu-limit-and-request/test/workload-exceeded/data.json
  rules/resources-cpu-limit-and-request/test/workload-exceeded/expected.json
  rules/resources-cpu-limit-and-request/test/workload-exceeded/input/deployment.yaml
  rules/resources-memory-limit-and-request/raw.rego
  rules/resources-memory-limit-and-request/test/workload-exceeded/data.json
  rules/resources-memory-limit-and-request/test/workload-exceeded/expected.json
  rules/resources-memory-limit-and-request/test/workload-exceeded/input/deployment.yaml
Labels: Refactoring, Tests

#534 Revert "Use cluster scope instead of AKS"
  controls/C-0239-preferusingdedicatedaksserviceaccounts.json
  controls/C-0240-ensurenetworkpolicyisenabledandsetasappropriate.json
  controls/C-0241-useazurerbacforkubernetesauthorization.json
  controls/C-0242-hostilemultitenantworkloads.json
  controls/C-0243-ensureimagevulnerabilityscanningusingazuredefenderimagescanningorathirdpartyprovider.json
  controls/C-0244-ensurekubernetessecretsareencrypted.json
  controls/C-0245-encrypttraffictohttpsloadbalancerswithtlscertificates.json
  controls/C-0247-restrictaccesstothecontrolplaneendpoint.json
  controls/C-0248-ensureclustersarecreatedwithprivatenodes.json
  controls/C-0249-restrictuntrustedworkloads.json
  controls/C-0250-minimizeclusteraccesstoreadonlyforazurecontainerregistryacr.json
  controls/C-0252-ensureclustersarecreatedwithprivateendpointenabledandpublicaccessdisabled.json
  controls/C-0254-enableauditlogs.json
  frameworks/cis-aks-t1.2.0.json
Labels: Refactoring

#535 Update pr-comments.yaml
  .github/workflows/pr-comments.yaml
Labels: Refactoring

#538 replace serviceaccountname with serviceAccountName
  rules/rule-access-dashboard-wl-v1/raw.rego
  rules/rule-access-dashboard-wl-v1/test/cronjob/expected.json
  rules/rule-access-dashboard-wl-v1/test/pod/expected.json
  rules/rule-access-dashboard-wl-v1/test/workload/expected.json
  rules/rule-access-dashboard/raw.rego
Labels: Refactoring
