Repository kubescape/regolibrary, pull requests merged in 2024-04, with the labels that each got.

#614 improve remediation - return fix path in every case
  rules/rule-allow-privilege-escalation/raw.rego
  rules/rule-allow-privilege-escalation/test/cronjob/expected.json
  rules/rule-allow-privilege-escalation/test/pod/expected.json
  rules/rule-allow-privilege-escalation/test/workloads/expected.json
Labels: enhancement, Review effort [1-5]: 2

#615 fix C-0069 - anonymous auth disabled by default
  rules/anonymous-requests-to-kubelet-updated/raw.rego
  rules/anonymous-requests-to-kubelet-updated/test/invalid-config-no-value/expected.json
  rules/anonymous-requests-to-kubelet-updated/test/no-cli-params/expected.json
  rules/anonymous-requests-to-kubelet-updated/test/valid-cli/input/kubelet-info.json
Labels: bug_fix, Review effort [1-5]: 2

#616 C-0048 - fix to valid remediation
  rules/alert-any-hostpath/raw.rego
  rules/alert-any-hostpath/test/deployment/expected.json
  rules/alert-any-hostpath/test/deployment/input/deployment.yaml
  rules/alert-any-hostpath/test/pod/expected.json
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#617 improve remediations - C-0020, C-0045
  rules/alert-mount-potential-credentials-paths/raw.rego
  rules/alert-mount-potential-credentials-paths/test/deployment_eks_failed/expected.json
  rules/alert-mount-potential-credentials-paths/test/deployment_eks_failed/input/deployment.yaml
  rules/alert-mount-potential-credentials-paths/test/pod_eks_failed/expected.json
  rules/alert-rw-hostpath/raw.rego
  rules/alert-rw-hostpath/test/deployment/expected.json
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#570 Support HTTPRoute in Gateway API
  controls/C-0266-exposuretointernet-gateway.json
  frameworks/security.json
  rules/exposure-to-internet-via-gateway-api/raw.rego
  rules/exposure-to-internet-via-gateway-api/rule.metadata.json
  rules/exposure-to-internet-via-gateway-api/test/failed_with_httproute-istio/expected.json
  rules/exposure-to-internet-via-gateway-api/test/failed_with_httproute-istio/input/deployment.yaml
  rules/exposure-to-internet-via-gateway-api/test/failed_with_httproute-istio/input/httproute.yaml
  rules/exposure-to-internet-via-gateway-api/test/failed_with_httproute-istio/input/service.yaml
  rules/exposure-to-internet-via-gateway-api/test/failed_with_httproute/expected.json
  rules/exposure-to-internet-via-gateway-api/test/failed_with_httproute/input/deployment.yaml
  rules/exposure-to-internet-via-gateway-api/test/failed_with_httproute/input/httproute.yaml
  rules/exposure-to-internet-via-gateway-api/test/failed_with_httproute/input/service.yaml
  rules/exposure-to-internet/raw.rego
  testrunner/opaprocessor/processorutils.go
Labels: enhancement, Review effort [1-5]: 3

#619 re-add attack track external-workload-with-cluster-takeover-roles
  attack-tracks/external-workload-with-cluster-takeover-roles.json
  controls/C-0256-exposuretointernet.json
  controls/C-0266-exposuretointernet-gateway.json
  controls/C-0267-workloadwithclustertakeoverroles.json
  rules/outdated-k8s-version/raw.rego
Labels: enhancement, Review effort [1-5]: 2

#618 remove armoBuiltin attribute
  frameworks/__YAMLscan.json
  frameworks/allcontrols.json
  frameworks/armobest.json
  frameworks/cis-aks-t1.2.0.json
  frameworks/cis-eks-t1.2.0.json
  frameworks/cis-v1.23-t1.0.1.json
  frameworks/clusterscan.json
  frameworks/devopsbest.json
  frameworks/mitre.json
  frameworks/nsaframework.json
  frameworks/security.json
  frameworks/soc2.json
  frameworks/workloadscan.json
Labels: enhancement, Review effort [1-5]: 1

#620 Add data in rest encryption control (C-0264) to security.json
  controls/C-0262-anonymousaccessisenabled.json
  frameworks/security.json
Labels: enhancement, Review effort [1-5]: 1
