Repository kubescape/regolibrary, pull requests merged in 2024-03, with the labels that each got.

#592 add C-0267 - Workload with cluster takeover roles
  controls/C-0267-workloadwithclustertakeoverroles.json
  rules/workload-with-cluster-takeover-roles/filter.rego
  rules/workload-with-cluster-takeover-roles/raw.rego
  rules/workload-with-cluster-takeover-roles/rule.metadata.json
  rules/workload-with-cluster-takeover-roles/test/fail-wl-creates-pod/expected.json
  rules/workload-with-cluster-takeover-roles/test/fail-wl-creates-pod/input/clusterrole.yaml
  rules/workload-with-cluster-takeover-roles/test/fail-wl-creates-pod/input/clusterrolebinding.yaml
  rules/workload-with-cluster-takeover-roles/test/fail-wl-creates-pod/input/file.yaml
  rules/workload-with-cluster-takeover-roles/test/fail-wl-creates-pod/input/sa.json
  rules/workload-with-cluster-takeover-roles/test/fail-wl-gets-secrets/expected.json
  rules/workload-with-cluster-takeover-roles/test/fail-wl-gets-secrets/input/clusterrole.yaml
  rules/workload-with-cluster-takeover-roles/test/fail-wl-gets-secrets/input/clusterrolebinding.yaml
  rules/workload-with-cluster-takeover-roles/test/fail-wl-gets-secrets/input/file.yaml
  rules/workload-with-cluster-takeover-roles/test/fail-wl-gets-secrets/input/sa.json
  rules/workload-with-cluster-takeover-roles/test/pass-wl-limited-permissions/expected.json
  rules/workload-with-cluster-takeover-roles/test/pass-wl-limited-permissions/input/clusterrole.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-limited-permissions/input/clusterrolebinding.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-limited-permissions/input/file.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-limited-permissions/input/sa.json
  rules/workload-with-cluster-takeover-roles/test/pass-wl-not-mount-sa-token/expected.json
  rules/workload-with-cluster-takeover-roles/test/pass-wl-not-mount-sa-token/input/clusterrole.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-not-mount-sa-token/input/clusterrolebinding.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-not-mount-sa-token/input/file.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-not-mount-sa-token/input/sa.json
  rules/workload-with-cluster-takeover-roles/test/pass-wl-rolebinding/expected.json
  rules/workload-with-cluster-takeover-roles/test/pass-wl-rolebinding/input/cluterrole.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-rolebinding/input/file.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-rolebinding/input/rolebinding.yaml
  rules/workload-with-cluster-takeover-roles/test/pass-wl-rolebinding/input/sa.json
  testrunner/go.mod
  testrunner/go.sum
Labels: documentation, enhancement, Review effort [1-5]: 4

#595 add control C-0272 - Workload with administrative roles
  controls/C-0272-workloadwithadministrativeroles.json
  rules/workload-with-administrative-roles/filter.rego
  rules/workload-with-administrative-roles/raw.rego
  rules/workload-with-administrative-roles/rule.metadata.json
  rules/workload-with-administrative-roles/test/fail-wl-creates-pod/expected.json
  rules/workload-with-administrative-roles/test/fail-wl-creates-pod/input/clusterrole.yaml
  rules/workload-with-administrative-roles/test/fail-wl-creates-pod/input/clusterrolebinding.yaml
  rules/workload-with-administrative-roles/test/fail-wl-creates-pod/input/file.yaml
  rules/workload-with-administrative-roles/test/fail-wl-creates-pod/input/sa.json
  rules/workload-with-administrative-roles/test/pass-wl-limited-permissions/expected.json
  rules/workload-with-administrative-roles/test/pass-wl-limited-permissions/input/clusterrole.yaml
  rules/workload-with-administrative-roles/test/pass-wl-limited-permissions/input/clusterrolebinding.yaml
  rules/workload-with-administrative-roles/test/pass-wl-limited-permissions/input/file.yaml
  rules/workload-with-administrative-roles/test/pass-wl-limited-permissions/input/sa.json
  rules/workload-with-administrative-roles/test/pass-wl-not-mount-sa-token/expected.json
  rules/workload-with-administrative-roles/test/pass-wl-not-mount-sa-token/input/clusterrole.yaml
  rules/workload-with-administrative-roles/test/pass-wl-not-mount-sa-token/input/clusterrolebinding.yaml
  rules/workload-with-administrative-roles/test/pass-wl-not-mount-sa-token/input/file.yaml
  rules/workload-with-administrative-roles/test/pass-wl-not-mount-sa-token/input/sa.json
  rules/workload-with-administrative-roles/test/pass-wl-rolebinding/expected.json
  rules/workload-with-administrative-roles/test/pass-wl-rolebinding/input/cluterrole.yaml
  rules/workload-with-administrative-roles/test/pass-wl-rolebinding/input/file.yaml
  rules/workload-with-administrative-roles/test/pass-wl-rolebinding/input/rolebinding.yaml
  rules/workload-with-administrative-roles/test/pass-wl-rolebinding/input/sa.json
Labels: documentation, enhancement, Review effort [1-5]: 4

#584 Revert "Adding "create release without system tests" gh action"
  .github/workflows/create-releas-without-tests.yaml
Labels: enhancement, Review effort [1-5]: 1

#596 add control C-0273 - outdated k8s version
  .github/workflows/create-release.yaml
  .github/workflows/pr-tests.yaml
  controls/C-0273-outdatedk8sversion.json
  rules/outdated-k8s-version/raw.rego
  rules/outdated-k8s-version/rule.metadata.json
  rules/outdated-k8s-version/test/fail/expected.json
  rules/outdated-k8s-version/test/fail/input/node.json
  rules/outdated-k8s-version/test/fail2/expected.json
  rules/outdated-k8s-version/test/fail2/input/node.json
  rules/outdated-k8s-version/test/pass/expected.json
  rules/outdated-k8s-version/test/pass/input/node.json
  scripts/validations.py
Labels: documentation, enhancement, Review effort [1-5]: 4

#597 add workflow to create release without system tests
  .github/workflows/create-release-without-st.yaml
Labels: enhancement, Review effort [1-5]: 4

#598 add new attack paths for security risks
  attack-tracks/external-wl-unauthenticated.json
  attack-tracks/external-wl-with-cluster-takeover-roles.json
  controls/C-0256-exposuretointernet.json
  controls/C-0267-workloadwithclustertakeoverroles.json
  frameworks/security.json
Labels: enhancement, Review effort [1-5]: 2

#599 update default sensitiveKeyNames list
  default-config-inputs.json
Labels: enhancement, Review effort [1-5]: 1

#600 rm roleref as reviewPath, return only subject to del
  rules/workload-with-cluster-takeover-roles/raw.rego
  rules/workload-with-cluster-takeover-roles/test/fail-wl-creates-pod/expected.json
  rules/workload-with-cluster-takeover-roles/test/fail-wl-gets-secrets/expected.json
Labels: enhancement, Review effort [1-5]: 2

#601 change control name
  controls/C-0256-exposuretointernet.json
  frameworks/clusterscan.json
  frameworks/security.json
Labels: enhancement, Review effort [1-5]: 1

#602 support ac flatten display of related resources
  .github/workflows/create-release-without-st.yaml
  .github/workflows/create-release.yaml
  .github/workflows/pr-tests.yaml
  controls/C-0267-workloadwithclustertakeoverroles.json
  gitregostore/gitstoremethods.go
  go.mod
  go.sum
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#603 Support v1 version as well
  rules/csistoragecapacity-in-default-namespace/rule.metadata.json
Labels: enhancement, Review effort [1-5]: 1

#604 add isFixedByNetworkPolicy indicator
  controls/C-0260-missingnetworkpolicy.json
Labels: enhancement, Review effort [1-5]: 1

#605 Regolibrary v2 - new relelase workflow
  .github/workflows/create-release-v2.yaml
  .github/workflows/create-release-without-st.yaml
  attack-tracks/external-wl-with-cluster-takeover-roles.json
  controls/C-0256-exposuretointernet.json
  controls/C-0267-workloadwithclustertakeoverroles.json
  gitregostore/datastructures.go
Labels: documentation, enhancement, Review effort [1-5]: 4

#606 fix workflow
  .github/workflows/create-release-v2.yaml
Labels: enhancement

#607 fix workflow
  .github/workflows/create-release-v2.yaml
Labels: bug_fix

#608 fix workflow
  .github/workflows/create-release-v2.yaml
Labels: enhancement

#610 add constructor for regolibrary V2
  gitregostore/datastructures.go
  gitregostore/gitstoremethods_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#611 upgrade module to v2
  gitregostore/datastructures.go
  go.mod
Labels: enhancement, Review effort [1-5]: 1

#609 Revert "removed control C-0264 from soc2 FW"
  frameworks/soc2.json
Labels: enhancement, Review effort [1-5]: 2

#613 Fix c0074
  rules/containers-mounting-docker-socket/raw.rego
  rules/containers-mounting-docker-socket/test/cronjob-containerd/expected.json
  rules/containers-mounting-docker-socket/test/cronjob-crio/expected.json
  rules/containers-mounting-docker-socket/test/cronjob/expected.json
  rules/containers-mounting-docker-socket/test/pod-containerd/expected.json
  rules/containers-mounting-docker-socket/test/pod-crio/expected.json
  rules/containers-mounting-docker-socket/test/pod/expected.json
  rules/containers-mounting-docker-socket/test/workloads-containerd/expected.json
  rules/containers-mounting-docker-socket/test/workloads-crio/expected.json
  rules/containers-mounting-docker-socket/test/workloads/expected.json
  rules/rule-allow-privilege-escalation/raw.rego
  rules/rule-allow-privilege-escalation/test/cronjob/expected.json
  rules/rule-allow-privilege-escalation/test/workloads/expected.json
Labels: enhancement, bug_fix, Review effort [1-5]: 2
