Repository kubescape/regolibrary, pull requests merged in 2024-02, with the labels that each got.

#571 Fixed reviewPaths
  rules/non-root-containers/raw.rego
Labels: bug_fix, Review effort [1-5]: 1

#572 change C-0035 name to `Administrative Roles`
  controls/C-0035-clusteradminbinding.json
  frameworks/__YAMLscan.json
  frameworks/allcontrols.json
  frameworks/armobest.json
  frameworks/clusterscan.json
  frameworks/mitre.json
  frameworks/nsaframework.json
Labels: enhancement, Review effort [1-5]: 1

#573 add security issues controls to security fw
  frameworks/security.json
Labels: enhancement, Review effort [1-5]: 2

#574 remove C-0264 from security fw
  frameworks/security.json
Labels: enhancement, Review effort [1-5]: 1

#576 Adding default exceptions
  exceptions/kubescape.json
Labels: enhancement, Review effort [1-5]: 2

#579 Adding kube-system exceptions
  exceptions/gke.json
  exceptions/kube-apiserver.json
  exceptions/kubescape.json
  exceptions/minikube.json
Labels: enhancement, Review effort [1-5]: 3

#580 fix C-0211 sysctls fixpath
  rules/set-sysctls-params/raw.rego
  rules/set-sysctls-params/test/cronjob/expected.json
  rules/set-sysctls-params/test/pod/expected.json
  rules/set-sysctls-params/test/workload/expected.json
Labels: enhancement, Review effort [1-5]: 2

#581 C-0012 add allowed values and keys lists to reduce false positives
  default-config-inputs.json
  rules/rule-credentials-configmap/raw.rego
  rules/rule-credentials-configmap/rule.metadata.json
  rules/rule-credentials-configmap/test/test-allowed-values-keys/data.json
  rules/rule-credentials-configmap/test/test-allowed-values-keys/expected.json
  rules/rule-credentials-configmap/test/test-allowed-values-keys/input/configmap.yaml
  rules/rule-credentials-in-env-var/raw.rego
  rules/rule-credentials-in-env-var/rule.metadata.json
  rules/rule-credentials-in-env-var/test/pod-allowed-values-keys/data.json
  rules/rule-credentials-in-env-var/test/pod-allowed-values-keys/expected.json
  rules/rule-credentials-in-env-var/test/pod-allowed-values-keys/input/pod.yaml
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#582 Remove default exceptions
  exceptions/kubescape.json
Labels: enhancement, Review effort [1-5]: 2

#583 Adding "create release without system tests" gh action
  .github/workflows/create-releas-without-tests.yaml
Labels: enhancement, Review effort [1-5]: 2

#587 rename C-0007 to `Roles with delete capabilities`
  controls/C-0007-datadestruction.json
  frameworks/allcontrols.json
  frameworks/clusterscan.json
  frameworks/mitre.json
Labels: enhancement, Review effort [1-5]: 1

#593 remove C-0001 from fws, don't delete for bc
  controls/C-0001-forbiddencontainerregistries.json
  controls/C-0091-cve202247633kyvernosignaturebypass.json
  default-config-inputs.json
  rules/rule-identify-blocklisted-image-registries-v1/raw.rego
  rules/rule-identify-blocklisted-image-registries-v1/rule.metadata.json
  rules/rule-identify-blocklisted-image-registries/raw.rego
  rules/rule-identify-blocklisted-image-registries/rule.metadata.json
  rules/rule-identify-blocklisted-image-registries/test/cronjob/data.json
  rules/rule-identify-blocklisted-image-registries/test/cronjob/expected.json
  rules/rule-identify-blocklisted-image-registries/test/cronjob/input/cronjob.yaml
  rules/rule-identify-blocklisted-image-registries/test/pod/data.json
  rules/rule-identify-blocklisted-image-registries/test/pod/expected.json
  rules/rule-identify-blocklisted-image-registries/test/pod/input/pod.yaml
  rules/rule-identify-blocklisted-image-registries/test/workloads/data.json
  rules/rule-identify-blocklisted-image-registries/test/workloads/expected.json
  rules/rule-identify-blocklisted-image-registries/test/workloads/input/deployment.yaml
Labels: documentation, enhancement, Review effort [1-5]: 3

#585 C-0013 - clarify remediation
  controls/C-0013-nonrootcontainers.json
Labels: enhancement, Review effort [1-5]: 1

#588 rename C-0002 to `Prevent containers from allowing command execution`
  controls/C-0002-execintocontainer.json
  frameworks/allcontrols.json
  frameworks/armobest.json
  frameworks/clusterscan.json
  frameworks/mitre.json
  frameworks/nsaframework.json
Labels: enhancement, Review effort [1-5]: 1
