Repository kubescape/regolibrary, pull requests merged in 2024-01, with the labels that each got.

#559 deprecate-old-rules
  controls/C-0002-execintocontainer.json
  controls/C-0007-datadestruction.json
  controls/C-0014-accesskubernetesdashboard.json
  controls/C-0015-listkubernetessecrets.json
  controls/C-0021-exposedsensitiveinterfaces.json
  controls/C-0031-deletekubernetesevents.json
  controls/C-0035-clusteradminbinding.json
  controls/C-0037-corednspoisoning.json
  controls/C-0042-sshserverrunninginsidecontainer.json
  controls/C-0053-accesscontainerserviceaccount.json
  controls/C-0063-portforwardingprivileges.json
  controls/C-0065-noimpersonation.json
  rules/access-container-service-account/raw.rego
  rules/access-container-service-account/rule.metadata.json
  rules/exec-into-container/raw.rego
  rules/exec-into-container/rule.metadata.json
  rules/exposed-sensitive-interfaces/raw.rego
  rules/exposed-sensitive-interfaces/rule.metadata.json
  rules/rule-access-dashboard/raw.rego
  rules/rule-access-dashboard/rule.metadata.json
  rules/rule-can-delete-k8s-events/raw.rego
  rules/rule-can-delete-k8s-events/rule.metadata.json
  rules/rule-can-impersonate-users-groups/raw.rego
  rules/rule-can-impersonate-users-groups/rule.metadata.json
  rules/rule-can-list-get-secrets/raw.rego
  rules/rule-can-list-get-secrets/rule.metadata.json
  rules/rule-can-portforward/raw.rego
  rules/rule-can-portforward/rule.metadata.json
  rules/rule-can-ssh-to-pod/raw.rego
  rules/rule-can-ssh-to-pod/rule.metadata.json
  rules/rule-can-update-configmap/raw.rego
  rules/rule-can-update-configmap/rule.metadata.json
  rules/rule-excessive-delete-rights/raw.rego
  rules/rule-excessive-delete-rights/rule.metadata.json
  rules/rule-list-all-cluster-admins/raw.rego
  rules/rule-list-all-cluster-admins/rule.metadata.json
Labels: enhancement

#558 fix C-0236 assisted remediation
  rules/verify-image-signature/raw.rego
Labels: bug_fix

#560 Improve c-0012
  default-config-inputs.json
  rules/rule-credentials-configmap/raw.rego
  rules/rule-credentials-configmap/rule.metadata.json
  rules/rule-credentials-in-env-var/raw.rego
  rules/rule-credentials-in-env-var/rule.metadata.json
  rules/rule-credentials-in-env-var/test/cronjob/expected.json
  rules/rule-credentials-in-env-var/test/deployment/expected.json
  rules/rule-credentials-in-env-var/test/pod/expected.json
  rules/rule-credentials-in-env-var/test/workloads/expected.json
Labels: enhancement

#564 Fixing C-0079 to properly detect CVE-2022-0185 on azure
  rules/CVE-2022-0185/raw.rego
  rules/CVE-2022-0185/test/test_azure_fail/expected.json
  rules/CVE-2022-0185/test/test_azure_fail/input/kernelvars.json
  rules/CVE-2022-0185/test/test_azure_fail/input/node.json
  rules/CVE-2022-0185/test/test_azure_pass/expected.json
  rules/CVE-2022-0185/test/test_azure_pass/input/kernelvars.json
  rules/CVE-2022-0185/test/test_azure_pass/input/node.json
  rules/CVE-2022-0185/test/test_generic_fail/expected.json
  rules/CVE-2022-0185/test/test_generic_fail/input/kernelvars.json
  rules/CVE-2022-0185/test/test_generic_fail/input/node.json
  rules/CVE-2022-0185/test/test_generic_pass/expected.json
  rules/CVE-2022-0185/test/test_generic_pass/input/kernelvars.json
  rules/CVE-2022-0185/test/test_generic_pass/input/node.json
Labels: Bug fix, Tests, bug_fix

#561 refactor non-root-containers
  controls/C-0013-nonrootcontainers.json
  controls/C-0211-applysecuritycontexttoyourpodsandcontainers.json
  controls/examples/c013.yaml
  rules/non-root-containers/raw.rego
  rules/non-root-containers/rule.metadata.json
  rules/non-root-containers/test/cronjob-runasuser/expected.json
  rules/non-root-containers/test/cronjob-runasuser/input/cronjob.yaml
  rules/non-root-containers/test/cronjob/expected.json
  rules/non-root-containers/test/cronjob/input/cronjob.yaml
  rules/non-root-containers/test/deployment-fail/expected.json
  rules/non-root-containers/test/deployment-fail/input/deployment.yaml
  rules/non-root-containers/test/deployment-fixed-path/expected.json
  rules/non-root-containers/test/deployment-fixed-path/input/deploy.yaml
  rules/non-root-containers/test/deployment-pass/expected.json
  rules/non-root-containers/test/deployment-pass/input/deployment.yaml
  rules/non-root-containers/test/deployment/expected.json
  rules/non-root-containers/test/pod/expected.json
  rules/non-root-containers/test/pod/input/pod.yaml
Labels: enhancement

#544 create documentation pipeline to update and maintain control docs
  .github/sync.yml
  .github/workflows/create-release.yaml
  .github/workflows/sync.yml
  scripts/mk-generator.py
  scripts/upload-readme.py
Labels: enhancement

#566 Adding control C-0265: detection of over-privileged system:authenticated group
  controls/C-0265-authenticateduserhasrbac.json
  frameworks/allcontrols.json
  frameworks/clusterscan.json
  frameworks/security.json
  rules/system-authenticated-allowed-to-take-over-cluster/raw.rego
  rules/system-authenticated-allowed-to-take-over-cluster/rule.metadata.json
  rules/system-authenticated-allowed-to-take-over-cluster/test/fail/expected.json
  rules/system-authenticated-allowed-to-take-over-cluster/test/fail/input/clusterrole.yaml
  rules/system-authenticated-allowed-to-take-over-cluster/test/fail/input/clusterrolebinding.yaml
  rules/system-authenticated-allowed-to-take-over-cluster/test/success/expected.json
  rules/system-authenticated-allowed-to-take-over-cluster/test/success/input/rolebinding.yaml
Labels: enhancement, Review effort [1-5]: 3

#568 Add controls to security framework
  frameworks/security.json
Labels: enhancement, Review effort [1-5]: 1
